CREATE USER cadmin WITH PASSWORD 'cadmin';

CREATE TABLE public.list_subscriptions (
    user_id bigint NOT NULL,
    subscription_id bigint NOT NULL
);

CREATE TABLE public.subscriptions (
    id bigint NOT NULL,
    subscription_name character varying(255)
);


ALTER TABLE public.subscriptions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.subscriptions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE SEQUENCE public.subscriptions_seq
    START WITH 1
    INCREMENT BY 50
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

CREATE TABLE public.users (
    id bigint NOT NULL,
    first_name character varying(255),
    last_name character varying(255),
    midle_name character varying(255)
);

ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
CREATE SEQUENCE public.users_seq
    START WITH 1
    INCREMENT BY 50
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

ALTER TABLE public.list_subscriptions OWNER TO cadmin;
ALTER TABLE public.subscriptions OWNER TO cadmin;
ALTER SEQUENCE public.subscriptions_seq OWNER TO cadmin;
ALTER TABLE public.users OWNER TO cadmin;
ALTER SEQUENCE public.users_seq OWNER TO cadmin;

SELECT pg_catalog.setval('public.subscriptions_id_seq', 1, true);
SELECT pg_catalog.setval('public.subscriptions_seq', 1, false);
SELECT pg_catalog.setval('public.users_id_seq', 1, false);
SELECT pg_catalog.setval('public.users_seq', 1, true);
ALTER TABLE ONLY public.list_subscriptions
    ADD CONSTRAINT list_subscriptions_pkey PRIMARY KEY (user_id, subscription_id);
ALTER TABLE ONLY public.subscriptions
    ADD CONSTRAINT subscriptions_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.subscriptions
    ADD CONSTRAINT subscriptions_unique UNIQUE (subscription_name);
ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.list_subscriptions
    ADD CONSTRAINT fkgx0y405e7l6o6v4ftkxk0cvku FOREIGN KEY (subscription_id) REFERENCES public.subscriptions(id);
ALTER TABLE ONLY public.list_subscriptions
    ADD CONSTRAINT fkt5f6rjyvijjwoxt6hw97desx9 FOREIGN KEY (user_id) REFERENCES public.users(id);

GRANT ALL PRIVILEGES ON DATABASE "music" to cadmin;
